[build]
  publish = "."
  command = "echo 'No build needed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form settings
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Enable form processing
[build.environment]
  # Increase the maximum file upload size to 10MB (Netlify's limit for free tier)
  NETLIFY_FORMS_MAX_FILE_SIZE = "10485760"  # 10MB in bytes
  
# Enable form submissions
[[plugins]]
  package = "@netlify/plugin-forms"
  
# Security headers for form submissions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"